version: '3.9'
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpass}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-studentdb}
      - MYSQL_USER=${MYSQL_USER:-student}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-studentpass}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../backend/.env
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  ai:
    build:
      context: ../ai
      dockerfile: Dockerfile
    env_file:
      - ../ai/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file:
      - ../frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
  mongo_data:

